version: '3.8'
services:
  db:
    container_name: postgres-16
    image: postgres:16
    volumes:
      - db_data_pg16:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data_pg16:
