# This docker-compose is development purposes only
version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    container_name: postgres-16
    image: postgres:16
    environment:
        POSTGRES_PASSWORD: password
    volumes:
      - db_data_pg16:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data_pg16:
