default: &default
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.week

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
