default: &default
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password

development:
  <<: *default
  host: localhost
  database: taskthing_development

test:
  <<: *default
  host: localhost
  database: taskthing_test

production:
  <<: *default
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  database: taskthing_production
