default: &default
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5434
  username: <%= ENV["TASKTHING_DATABASE_USERNAME"] %>
  password: <%= ENV["TASKTHING_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: taskthing_development

test:
  <<: *default
  database: taskthing_test

production:
  <<: *default
  database: taskthing_production
  port: 5432
