service: taskthing
image: adillari/taskthing
servers:
  web:
    hosts:
      - <%= ENV["TASKTHING_HOST"] %>
    options:
      add-host: host.docker.internal:host-gateway
  job:
    hosts:
      - <%= ENV["TASKTHING_HOST"] %>
    cmd: bundle exec sidekiq
    options:
      add-host: host.docker.internal:host-gateway
registry:
  username: adillari
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
builder:
  arch: amd64
proxy:
  app_port: 3000
  forward_headers: true
aliases:
  console: app exec -i --reuse "bin/rails console"
# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets
# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
# volumes:
#   - "taskthing_storage:/rails/storage"
